### ISSUE TITLE
Tematy Projektów

### ISSUE THREAD

**Issue by mmagnuski** [mmagnuski/emosie#4]
W poniższym google spreadsheet'cie wpisujecie swoje plany na projekt (są już tam przykłady abyście wiedzieli jak się wpisać):
https://docs.google.com/spreadsheets/d/1EI99eyVoAa2VFjm4wQfOcFeDBwGJBtCAnCvfas-j-Kc/edit?usp=sharing

* musicie korzystać przy logowaniu z maila w domenie swps inaczej nie będziecie mogli edytować
* zachęcam do eksperymentowania z feature dropout, który prezentuję w notebook'u 7 bonusowym:
  ```python
  model.add(Dropout(dropout_rate, noise_shape=(None, 1, 1, n_filters)))
  ```
  w powyższym fragmencie musicie tylko zmienić:
  - `dropout_rate` tzn. prawdopodobieństwo zgubienia filtra (możecie wybierać z wartości między `0.2` a `0.8`, wyższe wartości mogą być zbyt ekstremalne, a niższe mogą nie dać obserwowalnych efektów)
  - `n_filters` - ile filtrów jest w poprzedniej warstwie splotowej (tzn. w ostatniej warstwie splotowej patrząc wstecz czyli "do góry" komórki w której definiujemy model)

**Comment by pbarkowski** [comment]
Mikołaj,
czy można "podkradać" Twoje przykłady? To co wymyślił `przykładowy_student4` jest bardzo bliskie modyfikacjom jakie chciałem wprowadzić (nie myślałem tylko o opcjonalnej zmianie 3, ale też jest ciekawa), także chętnie przygarnę :)

**Comment by mmagnuski** [comment]
@pbarkowski Jasne, można korzystać z przykładów. W ostatecznym rozrachunku ważne jest tylko aby każdy student (prawdziwy, nie przykładowy) miał coś innego (pojedyncze zmiany mogą się pokrywać, ale ich konkretne kombinacje nie).

**Comment by xxxena** [comment]
błąd :(
HELP
![image](https://user-images.githubusercontent.com/23745354/41250464-4d8d5aa2-6db7-11e8-8b39-b15922618bc1.png)

**Comment by xxxena** [comment]
Czy  projekt wysyłamy na maila? Jeżeli tak, to pod jakim tytułem?
W tym pliku gdzie wpisujemy plany na projekt musimy również wpisać wyniki (tzn. uwagi i poprawność która nam wyszła)?
Jaką poprawność uważamy za OK?

**Comment by mmagnuski** [comment]
@xxxena 
Po pierwsze: w waszym projekcie nie chodzi aby uzyskać jak najlepszą poprawność, ale aby przetestować jak zmiany w oryginalnej sieci, którą znacie przekładają się na jej poprawność - podnoszą ją a może obniżają?
W związku z tym ważne jest aby trening był podobny do sieci na której się wzorujecie (którą zmieniacie) - tzn. aby np sieć była trenowana przez podobną ilość epok, podobnym optymalizatorem (np. `'adam'`), chyba że optymalizator jest przedmiotem zmian w oryginalnej sieci..
Projekt wysyłać będziecie na platformę, ale o tym w przyszłym tygodniu. Na realizacje projektu macie jeszcze co najmniej 2.5 tygodnia, a to nie jest dużo pracy, także czasu jest jeszcze sporo.

**Comment by NataliaTabi** [comment]
Jest już dostępna platforma na którą mamy wrzucać te prace?

**Comment by mmagnuski** [comment]
@NataliaTabi tak, informowałem o tym mailowo.

**Comment by zkostrzewa** [comment]
Kochani! 
Czy tylko ja na platformie po wejściu do "Projekt końcowy" mam jedno wielkie nic?

**Comment by mmagnuski** [comment]
@zkostrzewa
Jak wygląda jedno wielkie nic? Czy problem został rozwiązany?

**Comment by zkostrzewa** [comment]
@mmagnuski 
ale jesteś szybki. Już skasowałam ten niepokojący post, bo już mam wszystko co trzeba. Martwi mnie tylko, że to dzisiaj do północy, a nie jutrzejsza północ. Chociaż powstaje filozoficzne pytanie do jakiego dnia należy północ? Kod już mam gotowy, ale nie mam gdzie go uruchomić, stąd moje troski związane z czasem.

**Comment by pbarkowski** [comment]
Ja również myślałem że projekty są do soboty do końca dnia :)

**Comment by mmagnuski** [comment]
To ja widocznie coś źle zaznaczyłem, ale i tak pewnie będę musiał przedłużyć także jeszcze kilka dni będę mógł Wam dać.

**Comment by olaartych** [comment]
Moje pytania być może powinny się pojawić już na zajęciach ale:
1. Czy ilość filtrów zawsze jest potęgą 2? Czy można ustawić na przykład 50?
2. Czy w jednej warstwie można dać max pooling, a w innej average pooling, ma to sens?
3. Czy każda kolejna warstwa zawsze ma więcej filtrów niż poprzednia?

**Comment by pbarkowski** [comment]
Ode mnie już - mam nadzieję! - ostatnie pytanie: czy w swoim projekcie wprowadzam zmiany względem bazowego modelu, ustawiam np. 35 epok i raportuję wyniki w arkuszu, czy też wzorem notebook7bonus staram się "wycisnąć" ile mogę?

I mała informacja ode mnie: po kilku godzinach walki z plikami desktop.ini oraz Thumbs.db, których w Windowsie w żaden sposób nie mogłem usunąć/zablokować, zmodyfikowałem nieco emosie.py:



dodałem warunek `if full_img_path[-4:] == '.jpg':`
przed liniami kodu:
```
imgs.append(img_to_array(load_img(full_img_path, target_size=resize)))
y.append(flt_idx)
```

**Comment by mmagnuski** [comment]
@olaartych 
1. nie musi to być potęga 2. Często robi się tak zwyczajowo, a po części pewnie ze względów obliczeniowych (obliczenia na wektorach o długości będącej potęgą 2 często są szybsze).
2. jak się chce to można :) Ostatnio nawet coraz częściej pomija się max pooling i zwiększ się krok (`stride`) warstw `Conv2D`. Ciekawiej jednak byłoby wszystkie maxpooling zamienić na averagepooling - wtedy można mieć lepszy ogląd tego, czy przekłada się to na zmianę w poprawności.
3. To konwencja. Generalnie ze względu na maxpooling (ale nie tylko) wielkość "map korelacyjnych" (wyników splotu) z kolejnymi warstwami sieci jest coraz mniejsza. W związku z tym zwiększ się liczbę tych map/filtrów. Ale podstawowa przyczyna jest taka, że prostych kategorii wzrokowych (linie, kąty) jest mniej niż konceptów wysokiego poziomu (kończyna, głowa, krzesło, woda, futro itp.). Dlatego aby móc uchwycić te koncepty potrzebujemy więcej filtrów. Ale w projekcie możecie robić jak Wam się podoba. Możesz zrobić nawet malejącą liczbę filtrów.

**Comment by mmagnuski** [comment]
@pbarkowski 
Najlepiej odtwarzać warunki treningu notebook'a, na którego sieci się opieracie. Tzn np. jeżeli modyfikujesz sieć z notebooka 7 to trenuj ją tak samo (więcej epok).
Wydawało mi się, że w tej funkcji z emosi jest selekcja po rozszerzeniu, ale widocznie nie ma - tak jak robisz jest ok. Możesz ew. rozszerzyć tę funkcjonalność do np.:

```python
extensions = ['.png', '.jpg', '.jpeg', '.bmp']
images = [fname for fname in images if any([fname.endswith(ext) for ext in extensions])]
```
(*nie pamiętam dokładnych nazw zmiennych w emosiach*) i wtedy zrobić np. pull request do repozytorium emosi i zastosujemy te zmiany (albo ja mogę zmienić bezpośrednio w emosiach).

**Comment by BarbZielinska** [comment]
Proszę o pomoc. Już wszystko pięknie działało do (prawie) samego końca, kiedy to musiałam zrobić upgrade tensorflow'a. Po serii zmian jestem w kropce, gdyż sprawdzając notebooka od początku już w tym momencie krzyczy mi nagle, że nie ma emosiów... :( 
![image](https://user-images.githubusercontent.com/23638226/42700289-925a3414-86c3-11e8-9da3-3cbee06ba661.png)

**Comment by BarbZielinska** [comment]
Proszę o pomoc. Już wszystko pięknie działało do (prawie) samego końca, kiedy to musiałam zrobić upgrade tensorflow'a. Po serii zmian jestem w kropce, gdyż sprawdzając notebooka od początku już w tym momencie krzyczy mi nagle, że nie ma emosiów... :(
![image](https://user-images.githubusercontent.com/23638226/42700445-10f4f430-86c4-11e8-9815-5ec2fd5f6905.png)

**Comment by mmagnuski** [comment]
@BarbZielinska 
A masz plik `emosie.py` w folderze z notebookiem? Musi nazywać się dokładnie `emosie.py`, a nie na przykład `emosie (1).py`.

**Comment by mmagnuski** [comment]
Kiedy piszesz w pythonie `import jakiśtammoduł` python najpierw sprawdza czy w obecnym folderze jest plik `jakiśtammoduł.py` albo folder `jakiśtammoduł` w którym znajduje się plik `__init__.py` (wtedy traktuje całą zawartość folderu jako bibliotekę), a następnie, jeżeli nic nie znalazł, sprawdza wszystkie foldery, które znajdują się w zmiennej środowiskowej `PYTHONPATH`. Jeżeli w żadnym nie znajdzie odpowiedniego pliku albo folderu dostajesz błąd `ModuleNotFoundError`, co jak nazwa błędu wskazuje świadczy o tym, że python nie może znaleźć tego modułu. 
Najprawdopodobniej nie masz po prostu pliku `emosie.py` w folderze z notebookiem.  
Druga opcja jest taka, że Twoja obecna ścieżka może różnić się od tej, w której jest notebook. Możesz sprawdzić w jakim folderze python obecnie "siedzi":
```python
import os
current_dir = os.getcwd()
print(current_dir)
```
a następnie sprawdzić czy w tym folderze znajduje się plik `emosie.py` albo po prostu zmienić obecny folder na ten, w którym są `emosie.py` np.:
```python
os.chdir(folder_w_którym_są_emosie)
```
Jeszcze inna opcja to dodanie do folderów przeszukiwanych przez pythona folderu, w którym są emosie:
```python
import sys
sys.path.append(folder_w_którym_są_emosie)
```
także możliwości jest dużo. :)

**Comment by BarbZielinska** [comment]
Plik był. O coś innego jeszcze chodziło, ale już sobie poradziłam. Niewykluczone, że zaraz znowu mnie coś wystraszy, to napiszę. :D

**Comment by mmagnuski** [comment]
@BarbZielinska 
To na czym u Ciebie polegał błąd? `os.getcwd()` pokazuje Ci folder `emosie-master` czyli folder ściągnięty z github'a, a w tym `emosie.py` są dopiero w podfolderze `notebooks`.

**Comment by karinczi** [comment]
Myślałam, że na początku chodzi o mój źle działający komputer, ale zainstalowałam WSZYSTKO od początku na innym by móc odpalić go na drugim komputerze i dalej mam dokładnie ten sam błąd. Tak wiem że już po czasie, za późno się zabrałam, ale chciałabym się z tym uporać
![image](https://user-images.githubusercontent.com/24210964/42724078-35b051d6-876c-11e8-8e37-01d8eaa23efe.png)

**Comment by karinczi** [comment]
![image](https://user-images.githubusercontent.com/24210964/42724084-4bee40fc-876c-11e8-83f2-527a653617ee.png)

**Comment by mmagnuski** [comment]
`PermissionError` to błąd dostępu do plików. Pliki są na komputerze ale dany użytkownik/aplikacja nie dostaje do nich dostępu od systemu. Najłatwiej rozwiązać problem otwierając wiersz polecenia z uprawnieniami administratora. Tutaj możesz sobie przczytać jak to zrobić:
https://stackoverflow.com/questions/43248141/how-can-i-run-jupyter-notebook-in-admin-privilege

**Comment by karinczi** [comment]
Właśnie to było pierwsze co zrobiłam, bo tak też podpowiadali mi znajomi z grupy, ale niestety nawet to nic nie daje.

**Comment by mmagnuski** [comment]
Jesteś pewna że zamknęłaś oryginalnego notebook'a, konsolę i odpaliłaś nową z uprawnieniami administratora i dopiero wtedy otworzyłas jupyter notebook i odpaliłaś notebook?
Upewnij się też czy emosie-master to nie jest na przykład przypadkiem plik .zip (chociaż coś takiego nie powinno się zdarzyć). A w innym wypadku, spróbuj najpierw w konsoli odpalić:
```
conda list PIL
```
jeżeli w kolumnie build channel nie będziesz miała `<pip>` to możesz zrobić tak:
```
conda uninstall PIL
```
a następnie:
```
pip install PIL
```

**Comment by karinczi** [comment]
Tak, na pewno robiłam tak jak piszesz Mikołaj. Spróbowałam drugiego sposobu i albo robię coś źle ( jest to bardziej niż bardzo możliwe) albo mam takiego pecha, że coś nie działa. POMOCY:(((
![image](https://user-images.githubusercontent.com/24210964/42728859-9fdf4388-87c5-11e8-8eb9-9fe23de1091a.png)

**Comment by mmagnuski** [comment]
zależy co pokazuje Ci pierwsza z komend tzn `conda list PIL`. Możesz spróbować np. `pip install pillow`. Ale to może nie jest problem, który sprawnie rozwiążemy przez github'a (długie odroczenia między krótkimi krokami/testami), szkoda że nie skorzystałaś wcześniej z konsultacji live.

**Comment by karinczi** [comment]
![image](https://user-images.githubusercontent.com/24210964/42731062-cfcd1bb6-8805-11e8-9aef-bd1a5b94e327.png)
to mi pokazuję, googlując problem też próbowałam drugiego sposobu. Oj bardzo szkoda, ale niestety byłam pochłonięta licencjatem i teraz bardzo tego żałuję. Ale nigdy wcześniej też nie miałam takiego problemu przy robieniu wcześniejszych projektów czy też zadań. I to jeszcze myślałam, że to z moim komputerem problem, bo tam panuje chaos, ale już zmieniłam i dalej jest to samo...

**Comment by mmagnuski** [comment]
W związku z tym, skoro masz zainstalowane pillow, a nie PIL, zrób tak:
```
conda uninstall pillow
pip install pillow
```
wersja pillow (też w skrócie PIL, to faktycznie nowsza wersja biblioteki PIL) na pip jest stabilniejsza od tej na condzie (chyba że już jest update). Ale nie gwarantuję, że to rozwiąże problem, bo `PermissionError` sugeruje błąd dostępu. Możesz spróbować też przenieść zdjęcia psokotów gdzieś indziej (ale też upewnij się na wszelki wypadek że są one rozpakowane). Możesz jeszcze dodatkowo pokazać co masz w zmiennej `dane`, której używasz w `load_images`. Upewnij się też że folder, z którego wczytujesz obrazy zawiera tylko obrazy a nie inne pliki.
