### ISSUE TITLE
Tematy Prezentacji

### ISSUE THREAD

**Issue by mmagnuski** [mmagnuski/emosie#5]
Poniżej przykładowe tematy. Pamiętajcie, że możecie zaproponować również swoje tematy, te są tylko pomocą dla Was gdybyście nie mieli pomysłu. Gdybyście mieli jakieś trudności z wybranym tematem możecie też konsultować się ze mną (termin konsultacji możemy uzgodnić poprzez e-mail).

* konkurs `ImageNet` i przykłady sieci, które go wygrywały
* architektura sieci `Inception` Google'a, architektura `ResNet` albo `DenseNet` (do wyboru jedna na prezentację, jest sporo materiałów popularnonaukowych na ten temat)
* detekcja/lokalizacja obiektów (np. sieć `YOLO`)
* segmentacja obrazu
* rozpoznawanie twarzy
* roboty (np. BostonDynamics) lub chatboty (Google Duplex)
* AlphaGo i AlphaZero albo inne przykłady AI grającego w gry (DeepMind ma np. całe środowisko do testowania AI w graniu w StarCraft'a II)
* autonomiczne samochody
* autoencoders
* Generative Adversarial Networks i ich zastosowania (to wiele tematów)

pomocne materiały:
* [two minute papers](https://www.youtube.com/channel/UCbfYPyITQ-7l4upoX8nvctg)
* [Siraj Raval](https://www.youtube.com/channel/UCWN3xxRkmTPmbKwht9FuE5A/videos)
* [Distil](https://distill.pub/)

**Comment by xxxena** [comment]
Kowalczyk, Zahrebelna - Autonomiczne samochody

**Comment by inezjaworska** [comment]
Grupa pierwsza - Jaworska + Kostrzewa - autonomiczne samochody również ;) Zakładam, że między grupami tematy mogą się powtarzać

**Comment by sylwiataczanowska** [comment]
Bryłka, Taczanowska - detekcja/lokalizacja obiektów (np. sieć YOLO)

**Comment by mmagnuski** [comment]
@inezjaworska 
Jeżeli uzgodnicie między grupami tak aby tematyka się nie nakładała to tak. Temat autonomicznych samochodów jest bardzo pojemny - ale musicie się porozumieć aby omówić różne zagadnienia.

**Comment by pbarkowski** [comment]
Artych, Barkowski - AlphaGo i AlphaZero albo inne przykłady AI grającego w gry

**Comment by Malgosia20** [comment]
ze względu na to, że Ksenii nie ma 18.06, musimy prezentować 11.06, jest taka szansa prawda?

**Comment by mmagnuski** [comment]
@Malgosia20 
Jasne, możemy tak zrobić, jeżeli dacie radę. Jakbyście miały pytania - dawajcie znać.

**Comment by inezjaworska** [comment]
My też chciałybyśmy z Zosią zrobić 11 czerwca prezentację, jeśli to nie problem, z tego samego powodu. A i dodatkowo, żeby tematy się nie nakładały to weźmiemy Boston Dynamics Robots

**Comment by mmagnuski** [comment]
@inezjaworska Ok.

**Comment by Fostaszewski** [comment]
Świerżewski, Ostaszewski - chatboty (Google Duplex)

**Comment by KlaudiaGluch** [comment]
Głuch, Rybus - konkurs ImageNet i przykłady sieci, które go wygrywały

**Comment by NataliaTabi** [comment]
Tabiszewska, Zielińska - rozpoznawanie twarzy

**Comment by mazaw** [comment]
Zawiślińska, Grochowska - detekcja/lokalizacja obiektów (np. sieć YOLO)

**Comment by MichalinaSawka** [comment]
Sawka i Leńska - konkurs ImageNet i przykłady sieci, które go wygrywały

**Comment by bar51015** [comment]
Kurczab - Boston Dynamics

**Comment by kkrystecka** [comment]
Krysyecka, Woźniak - autoencoders

**Comment by KajaKarmel** [comment]
Karmel- Generative Adversarial Networks (jeśli ktoś chce się na szybko do mnie przyłączyć to zapraszam)
Edit: Robię razem z Emilią Szczuchniak

**Comment by KorneliaSiemiaszko** [comment]
Tarasiewicz, Siemiaszko - Roboty (poza boston dynamics) + etyka
